(define
    (problem a_problem)
    (:domain delivery)
    ;(:situation <situation_name>) ;deprecated
    (:objects vehicle1 - carrier
        one two three - location
        package1 - item)
    (:init
        (adjacent one one two one) 
        (adjacent one one one two)
        (adjacent one one two two) 
        (adjacent two one one one)
        (adjacent two one one three)  
        (adjacent two one one two)
        (adjacent two one two two)  
        (adjacent two one three two)  
        (adjacent three one two two)
        (adjacent three one two one)
        (adjacent three one three two)
        (adjacent one three one two)
        (adjacent one three two two)
        (adjacent one three two three)
        (adjacent two three one three)
        (adjacent two three one two)
        (adjacent two three two two)
        (adjacent two three three two)
        (adjacent two three three three)

        (item-at package1 one two)
        (carrier-at vehicle1 two three)
        (= (fuel-level vehicle1) 100)
        (= (item-weight package1) 5)
        (= (carrier-capacity vehicle1) 15)
        (= (carrier-speed vehicle1) 100)
        (= (fuel-used vehicle1) 0)
    )
    (:goal (and
            (item-at-carrier package1 vehicle1) 
            (carrier-at vehicle1 three three)
        )
    )
)