(define
    (problem a_problem)
    (:domain delivery)

    (:objects 
        car1 car2 car3 -car 
        dbjdbvjbadjkvb
        motorbike1 motorbike2 motorbike3 -motorbike
        one two three four five six seven eight nine ten eleven twelve thirteen -location
        fourteen fifteen sixteen seventeen eighteen nineteen twenty twentyone -location
        twentytwo twentythree twentyfour twentyfive - location
        package1  package2 package3 package4 package5 package6 package7 - item)
    (:init
        ;scope of car1
        (adjacent car1 one two)
        (adjacent car1 two one)
        (adjacent car1 one one)
        (adjacent car1 two three)
        (adjacent car1 three two)
        (adjacent car1 two two)
        (adjacent car1 three four)
        (adjacent car1 four three)
        (adjacent car1 three three)
        (adjacent car1 four five)
        (adjacent car1 five four)
        (adjacent car1 four four)
        
        ;scope of car2
        (adjacent car2 five six)
        (adjacent car2 six five)
        (adjacent car2 five five)
        (adjacent car2 six seven)
        (adjacent car2 seven six)
        (adjacent car2 six six)
        (adjacent car2 seven eight)
        (adjacent car2 eight seven)
        (adjacent car2 seven seven)
        (adjacent car2 eight nine)
        (adjacent car2 nine eight)
        (adjacent car2 eight eight)
        (adjacent car2 nine ten)
        (adjacent car2 ten nine)
        (adjacent car2 nine nine)

        ;scope of motorbike1
        (adjacent motorbike1 ten eleven)
        (adjacent motorbike1 eleven ten)
        (adjacent motorbike1 ten ten)
        (adjacent motorbike1 eleven twelve)
        (adjacent motorbike1 twelve eleven)
        (adjacent motorbike1 eleven eleven)
        (adjacent motorbike1 twelve thirteen)
        (adjacent motorbike1 thirteen twelve)
        (adjacent motorbike1 twelve twelve)
        (adjacent motorbike1 thirteen fourteen)
        (adjacent motorbike1 fourteen thirteen)
        (adjacent motorbike1 thirteen thirteen)
        (adjacent motorbike1 fourteen fifteen)
        (adjacent motorbike1 fifteen fourteen)
        (adjacent motorbike1 fourteen fourteen)

        ;scope of motorbike2
        (adjacent motorbike2 fifteen sixteen)
        (adjacent motorbike2 sixteen fifteen)
        (adjacent motorbike2 fifteen fifteen)
        (adjacent motorbike2 sixteen seventeen)
        (adjacent motorbike2 seventeen sixteen)
        (adjacent motorbike2 sixteen sixteen)
        (adjacent motorbike2 seventeen eighteen)
        (adjacent motorbike2 eighteen seventeen)
        (adjacent motorbike2 seventeen seventeen)
        (adjacent motorbike2 eighteen nineteen)
        (adjacent motorbike2 nineteen eighteen)
        (adjacent motorbike2 eighteen eighteen)
        (adjacent motorbike2 nineteen twenty)
        (adjacent motorbike2 twenty nineteen)
        (adjacent motorbike2 nineteen nineteen)
        (adjacent motorbike2 twenty twenty)

        ;scope of motorbike3
        (adjacent motorbike3 fifteen sixteen)
        (adjacent motorbike3 sixteen fifteen)
        (adjacent motorbike3 fifteen fifteen)
        (adjacent motorbike3 sixteen seventeen)
        (adjacent motorbike3 seventeen sixteen)
        (adjacent motorbike3 sixteen sixteen)
        (adjacent motorbike3 seventeen eighteen)
        (adjacent motorbike3 eighteen seventeen)
        (adjacent motorbike3 seventeen seventeen)
        (adjacent motorbike3 eighteen nineteen)
        (adjacent motorbike3 nineteen eighteen)
        (adjacent motorbike3 eighteen eighteen)
        (adjacent motorbike3 nineteen twenty)
        (adjacent motorbike3 twenty nineteen)
        (adjacent motorbike3 nineteen nineteen)
        (adjacent motorbike3 twenty twenty)

        ;scope of car3
        (adjacent car3 one two)
        (adjacent car3 two one)
        (adjacent car3 one one)
        (adjacent car3 two three)
        (adjacent car3 three two)
        (adjacent car3 two two)
        (adjacent car3 three four)
        (adjacent car3 four three)
        (adjacent car3 three three)
        (adjacent car3 four five)
        (adjacent car3 five four)
        (adjacent car3 four four)
        (adjacent car3 five six)
        (adjacent car3 six five)
        (adjacent car3 five five)
        (adjacent car3 six seven)
        (adjacent car3 seven six)
        (adjacent car3 six six)
        (adjacent car3 seven eight)
        (adjacent car3 eight seven)
        (adjacent car3 seven seven)
        (adjacent car3 eight nine)
        (adjacent car3 nine eight)
        (adjacent car3 eight eight)
        (adjacent car3 nine ten)
        (adjacent car3 ten nine)
        (adjacent car3 nine nine)
        (adjacent car3 ten eleven)
        (adjacent car3 eleven ten)
        (adjacent car3 ten ten)
        (adjacent car3 eleven twelve)
        (adjacent car3 twelve eleven)
        (adjacent car3 eleven eleven)
        (adjacent car3 twelve thirteen)
        (adjacent car3 thirteen twelve)
        (adjacent car3 twelve twelve)
        (adjacent car3 thirteen fourteen)
        (adjacent car3 fourteen thirteen)
        (adjacent car3 thirteen thirteen)
        (adjacent car3 fourteen fifteen)
        (adjacent car3 fifteen fourteen)
        (adjacent car3 fourteen fourteen)
        (adjacent car3 fifteen sixteen)
        (adjacent car3 sixteen fifteen)
        (adjacent car3 fifteen fifteen)
        (adjacent car3 sixteen seventeen)
        (adjacent car3 seventeen sixteen)
        (adjacent car3 sixteen sixteen)
        (adjacent car3 seventeen eighteen)
        (adjacent car3 eighteen seventeen)
        (adjacent car3 seventeen seventeen)
        (adjacent car3 eighteen nineteen)
        (adjacent car3 nineteen eighteen)
        (adjacent car3 eighteen eighteen)
        (adjacent car3 nineteen twenty)
        (adjacent car3 twenty nineteen)
        (adjacent car3 nineteen nineteen)
        (adjacent car3 twenty twenty)
        
        ;initial loca3ions
        (carrier-at car1 one one)
        (carrier-at car2 five five)
        (carrier-at motorbike1 ten ten)
        (carrier-at motorbike2 fifteen fifteen)
        (carrier-at motorbike3 nineteen twenty)
        (carrier-at car3 fifteen fifteen)

        ;Items
        (= (item-weight package1) 2)
        (= (item-weight package2) 2)
        (= (item-weight package3) 2)
        (= (item-weight package4) 2)
        (= (item-weight package5) 2)
        (= (item-weight package6) 2)
        (= (item-weight package7) 2)
        (item-at package1 three four)
        (item-at package2 seven six)
        (item-at package3 eleven twelve)
        (item-at package4 fifteen fifteen)
        (item-at package5 four five)
        (item-at package6 twenty twenty)
        (item-at package7 four four)
        
        ;Car1
        (= (item-pick-speed car1) 2)
        (= (item-drop-speed car1) 2)
        (= (fuel-level car1) 50)
        (= (carrier-capacity car1) 15)
        (= (carrier-speed car1) 50)
        (= (fuel-used car1) 0)
        (= (carrier-weight car1) 0)

        ;Car2
        (= (item-pick-speed car2) 2)
        (= (item-drop-speed car2) 2)
        (= (fuel-level car2) 50)
        (= (carrier-capacity car2) 15)
        (= (carrier-speed car2) 50)
        (= (fuel-used car2) 0)
        (= (carrier-weight car2) 0)

        ;Car3
        (= (item-pick-speed car3) 2)
        (= (item-drop-speed car3) 2)
        (= (fuel-level car3) 200)
        (= (carrier-capacity car3) 15)
        (= (carrier-speed car3) 50)
        (= (fuel-used car3) 0)
        (= (carrier-weight car3) 0)

        ;Motorbike1
        (= (item-pick-speed motorbike1) 2)
        (= (item-drop-speed motorbike1)2)
        (= (fuel-level motorbike1) 25)
        (= (carrier-capacity motorbike1) 5)
        (= (carrier-speed motorbike1) 70)
        (= (fuel-used motorbike1) 0)
        (= (carrier-weight motorbike1) 0)

        ;Motorbike2
        (= (item-pick-speed motorbike2) 2)
        (= (item-drop-speed motorbike2)2)
        (= (fuel-level motorbike2) 25)
        (= (carrier-capacity motorbike2) 5)
        (= (carrier-speed motorbike2) 70)
        (= (fuel-used motorbike2) 0)
        (= (carrier-weight motorbike2) 0)

        ;Motorbike3
        (= (item-pick-speed motorbike3) 2)
        (= (item-drop-speed motorbike3)2)
        (= (fuel-level motorbike3) 8)
        (= (carrier-capacity motorbike3) 5)
        (= (carrier-speed motorbike3) 70)
        (= (fuel-used motorbike3) 0)
        (= (carrier-weight motorbike3) 0)
    )
    (:goal (and

            ;(carrier-at car1 three three)
            (item-at package1 four five)
            (item-at package2 eight eight)
            (item-at package3 fourteen fifteen)
            (item-at package4 twenty nineteen)
            (item-at package5 one one)
            (item-at package6 fifteen sixteen)
            (item-at package7 five five)
        )
    )
    (:metric minimize (total-fuel-used))
)